name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*" # 只监听 v 开头的 tag，比如 v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER
    permissions:
      contents: write
      issues: write
    env:
      IMAGE_PREFIX: mikumifa/bili-ticker-storm

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Build and push ticket-master image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: master.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-master:latest
            ${{ env.IMAGE_PREFIX }}-master:${{ env.TAG }}

      - name: Build and push ticket-worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-worker:latest
            ${{ env.IMAGE_PREFIX }}-worker:${{ env.TAG }}

      - name: Build and push gt-python image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: python.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-gt-python:latest
            ${{ env.IMAGE_PREFIX }}-gt-python:${{ env.TAG }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Helm lint
        run: helm lint ./helm

      - name: Package Helm chart
        run: helm package helm/ -d packaged-charts --version ${{ env.TAG }}

      - name: Generate or update index.yaml
        run: |
          helm repo index packaged-charts --url https://mikumifa.github.io/biliTickerStorm/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged-charts
          publish_branch: gh-pages